### ISSUE TITLE
You might want to change the shebang

### ISSUE THREAD

**Issue by Immortalin** [geo7/spacemacs_ubuntu_scripts#1]
`#!/usr/bin/env bash` is supposedly better. See [this](https://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang)

**Comment by geo7** [comment]
@Immortalin good shout, I'll switch that over later :+1:

**Comment by geo7** [comment]
cheers

https://github.com/geo7/spacemacs_ubuntu_scripts/commit/bc6bbf36636915629e14673427216fcbb9983749
